language: python
python:
  - "2.7"

# command to let run a real GUI application or web browser
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

# command to install dependencies
install: "pip install -r requirements.txt"

before_script: 
   - autopep8 -ir *
   - flake8 --max-complexity=6 --exclude=*.txt,*.md,*.sh --max-line-length=200 *
  
# command to run tests
script: 
   - lettuce AceptanceTest
   - cd UnitTest
   - python -m unittest TestFiguras TestFiguras2
   - coverage run --branch TestFiguras.py
   - coverage report -m
   - coverage run --branch TestFiguras2.py
   - coverage report -m
#   - python testSelenium.py
